### PR TITLE
Fixes warnings in React Native 0.25.

### PR DESCRIPTION
**Pull request by wootwoot1234**
Changed the way react native and react are imported to fix warning in React Native 0.25.

### CODE REVIEW

**Comment by marcosinigaglia** [comment]
Hi @wootwoot1234 , are you interested to create a new library with the latest pull requests?

**Comment by wootwoot1234** [comment]
I'm not sure what you mean? Do you mean fork the project and add these changes?

**Comment by marcosinigaglia** [comment]
Yes, I think the owner no longer supports this module.

**Comment by wootwoot1234** [comment]
@marcosinigaglia here you go: https://github.com/wootwoot1234/react-native-progress-bar

@lwansbrough can you accept this pull request and update the version on npm?

**Comment by marcosinigaglia** [comment]
@wootwoot1234 do you have publish on npm your version?

**Comment by wootwoot1234** [comment]
Try this for now:

``` shell
npm install --save react-native-progress-bar@https://github.com/wootwoot1234/react-native-progress-bar.git
```

**Pull request merged**
